name: Deprecate Old NPM Package Versions
on:
  push:
    branches:
      - master

jobs:
  deprecate:
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm ci

    - name: npm deprecate old versions
      run: |
        const execSync = require('child_process').execSync;

        const versionsJSON = execSync('npm view homebridge-nordpool-baltics versions --json');
        let versions = JSON.parse(versionsJSON);
        versions.sort();

        versions = versions.slice(0, versions.length - 3);

        for(let i=0; i < versions.length; i++) {
            execSync(`npm deprecate homebridge-nordpool-baltics@"${versions[i]}" "This version is deprecated, please update to the latest version."`);
        }
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
